// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvyJd5qjpviQ3CYLSR_PrWFj4MHMPhhk',
    appId: '1:473712425330:web:e8ecc937a558533bc605eb',
    messagingSenderId: '473712425330',
    projectId: 'umatna-trial-2',
    authDomain: 'umatna-trial-2.firebaseapp.com',
    storageBucket: 'umatna-trial-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPXlnn82Olps26d9az5Y-KOBkT4FbeFc',
    appId: '1:473712425330:android:6f5969d5d79a1025c605eb',
    messagingSenderId: '473712425330',
    projectId: 'umatna-trial-2',
    storageBucket: 'umatna-trial-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8syP0m_GvV5aSsx6b9fYDsuCQ2esR2Ok',
    appId: '1:473712425330:ios:6413369240e6f54dc605eb',
    messagingSenderId: '473712425330',
    projectId: 'umatna-trial-2',
    storageBucket: 'umatna-trial-2.appspot.com',
    iosBundleId: 'com.example.umatnaTrial2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8syP0m_GvV5aSsx6b9fYDsuCQ2esR2Ok',
    appId: '1:473712425330:ios:6413369240e6f54dc605eb',
    messagingSenderId: '473712425330',
    projectId: 'umatna-trial-2',
    storageBucket: 'umatna-trial-2.appspot.com',
    iosBundleId: 'com.example.umatnaTrial2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOvyJd5qjpviQ3CYLSR_PrWFj4MHMPhhk',
    appId: '1:473712425330:web:ce7faa9927ab708ec605eb',
    messagingSenderId: '473712425330',
    projectId: 'umatna-trial-2',
    authDomain: 'umatna-trial-2.firebaseapp.com',
    storageBucket: 'umatna-trial-2.appspot.com',
  );
}
